# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desk.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(330, 620, 75, 23))
        self.Add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Add.setObjectName("Add")
        self.Quit = QtWidgets.QPushButton(self.centralwidget)
        self.Quit.setGeometry(QtCore.QRect(640, 580, 75, 23))
        self.Quit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Quit.setObjectName("Quit")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(440, 620, 71, 21))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 620, 71, 21))
        self.label_2.setObjectName("label_2")
        self.Follow = QtWidgets.QPushButton(self.centralwidget)
        self.Follow.setGeometry(QtCore.QRect(540, 580, 75, 23))
        self.Follow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Follow.setObjectName("Follow")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(630, 620, 101, 23))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setObjectName("lcdNumber")
        self.Allin = QtWidgets.QPushButton(self.centralwidget)
        self.Allin.setGeometry(QtCore.QRect(330, 580, 75, 23))
        self.Allin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Allin.setObjectName("Allin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 981, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desk.PNG"))
        self.label.setObjectName("label")
        self.Double = QtWidgets.QPushButton(self.centralwidget)
        self.Double.setGeometry(QtCore.QRect(440, 580, 75, 23))
        self.Double.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Double.setObjectName("Double")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_6.setGeometry(QtCore.QRect(500, 180, 61, 81))
        self.graphicsView_6.setStyleSheet("")
        self.graphicsView_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_7.setGeometry(QtCore.QRect(430, 180, 61, 81))
        self.graphicsView_7.setStyleSheet("")
        self.graphicsView_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(360, 180, 61, 81))
        self.graphicsView.setStyleSheet("")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_8.setGeometry(QtCore.QRect(640, 180, 61, 81))
        self.graphicsView_8.setStyleSheet("")
        self.graphicsView_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_9.setGeometry(QtCore.QRect(570, 180, 61, 81))
        self.graphicsView_9.setStyleSheet("")
        self.graphicsView_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.graphicsView_9.setObjectName("graphicsView_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Quit.setText(_translate("MainWindow", "Quit"))
        self.label_2.setText(_translate("MainWindow", "你的筹码："))
        self.Follow.setText(_translate("MainWindow", "Follow"))
        self.Allin.setText(_translate("MainWindow", "All In"))
        self.Double.setText(_translate("MainWindow", "Double"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))


