# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desk.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_desk(object):
    def setupUi(self, desk):
        desk.setObjectName("desk")
        desk.resize(1055, 708)
        self.centralwidget = QtWidgets.QWidget(desk)
        self.centralwidget.setObjectName("centralwidget")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(330, 620, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(12)
        self.Add.setFont(font)
        self.Add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Add.setObjectName("Add")
        self.Quit = QtWidgets.QPushButton(self.centralwidget)
        self.Quit.setGeometry(QtCore.QRect(640, 580, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(12)
        self.Quit.setFont(font)
        self.Quit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Quit.setObjectName("Quit")
        self.Add_Chip = QtWidgets.QSpinBox(self.centralwidget)
        self.Add_Chip.setGeometry(QtCore.QRect(440, 620, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Add_Chip.setFont(font)
        self.Add_Chip.setFrame(True)
        self.Add_Chip.setMaximum(100000)
        self.Add_Chip.setSingleStep(5)
        self.Add_Chip.setObjectName("Add_Chip")
        self.My_Chips_label = QtWidgets.QLabel(self.centralwidget)
        self.My_Chips_label.setGeometry(QtCore.QRect(540, 620, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(12)
        self.My_Chips_label.setFont(font)
        self.My_Chips_label.setObjectName("My_Chips_label")
        self.Follow = QtWidgets.QPushButton(self.centralwidget)
        self.Follow.setGeometry(QtCore.QRect(540, 580, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(12)
        self.Follow.setFont(font)
        self.Follow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Follow.setObjectName("Follow")
        self.My_Chips = QtWidgets.QLCDNumber(self.centralwidget)
        self.My_Chips.setGeometry(QtCore.QRect(630, 620, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.My_Chips.setFont(font)
        self.My_Chips.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.My_Chips.setStyleSheet("")
        self.My_Chips.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.My_Chips.setFrameShadow(QtWidgets.QFrame.Plain)
        self.My_Chips.setLineWidth(3)
        self.My_Chips.setDigitCount(5)
        self.My_Chips.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.My_Chips.setProperty("value", 0.0)
        self.My_Chips.setObjectName("My_Chips")
        self.Allin = QtWidgets.QPushButton(self.centralwidget)
        self.Allin.setGeometry(QtCore.QRect(330, 580, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Allin.setFont(font)
        self.Allin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Allin.setObjectName("Allin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 981, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desk.PNG"))
        self.label.setObjectName("label")
        self.Double = QtWidgets.QPushButton(self.centralwidget)
        self.Double.setGeometry(QtCore.QRect(440, 580, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(12)
        self.Double.setFont(font)
        self.Double.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Double.setObjectName("Double")
        self.Card1 = QtWidgets.QLabel(self.centralwidget)
        self.Card1.setGeometry(QtCore.QRect(360, 150, 61, 81))
        self.Card1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Card1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Card1.setLineWidth(1)
        self.Card1.setMidLineWidth(0)
        self.Card1.setText("")
        self.Card1.setObjectName("Card1")
        self.Card2 = QtWidgets.QLabel(self.centralwidget)
        self.Card2.setGeometry(QtCore.QRect(430, 150, 61, 81))
        self.Card2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Card2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Card2.setLineWidth(1)
        self.Card2.setMidLineWidth(0)
        self.Card2.setText("")
        self.Card2.setObjectName("Card2")
        self.Card3 = QtWidgets.QLabel(self.centralwidget)
        self.Card3.setGeometry(QtCore.QRect(500, 150, 61, 81))
        self.Card3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Card3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Card3.setLineWidth(1)
        self.Card3.setMidLineWidth(0)
        self.Card3.setText("")
        self.Card3.setObjectName("Card3")
        self.Card4 = QtWidgets.QLabel(self.centralwidget)
        self.Card4.setGeometry(QtCore.QRect(570, 150, 61, 81))
        self.Card4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Card4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Card4.setLineWidth(1)
        self.Card4.setMidLineWidth(0)
        self.Card4.setText("")
        self.Card4.setObjectName("Card4")
        self.Card5 = QtWidgets.QLabel(self.centralwidget)
        self.Card5.setGeometry(QtCore.QRect(640, 150, 61, 81))
        self.Card5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Card5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Card5.setLineWidth(1)
        self.Card5.setMidLineWidth(0)
        self.Card5.setText("")
        self.Card5.setObjectName("Card5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 580, 75, 23))
        self.pushButton.setObjectName("pushButton")
        desk.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(desk)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        desk.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(desk)
        self.statusbar.setObjectName("statusbar")
        desk.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(desk)
        QtCore.QMetaObject.connectSlotsByName(desk)

    def retranslateUi(self, desk):
        _translate = QtCore.QCoreApplication.translate
        desk.setWindowTitle(_translate("desk", "MainWindow"))
        self.Add.setText(_translate("desk", "Add"))
        self.Quit.setText(_translate("desk", "Quit"))
        self.My_Chips_label.setText(_translate("desk", "My Chips："))
        self.Follow.setText(_translate("desk", "Follow"))
        self.Allin.setText(_translate("desk", "All In"))
        self.Double.setText(_translate("desk", "Double"))
        self.pushButton.setText(_translate("desk", "PushButton"))
        self.menu.setTitle(_translate("desk", "菜单"))

